# Generated by Django 6.0.6 on 2026-08-03 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_secure_exchange_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('FUTURES', 'USD-M Futures'), ('SPOT', 'Spot')], max_length=16)),
                ('symbol', models.CharField(max_length=32)),
                ('trade_id', models.BigIntegerField()),
                ('order_id', models.BigIntegerField(blank=True, null=True)),
                ('side', models.CharField(max_length=8)),
                ('price', models.DecimalField(decimal_places=12, max_digits=32)),
                ('quantity', models.DecimalField(decimal_places=12, max_digits=32)),
                ('quote_quantity', models.DecimalField(decimal_places=12, default=0, max_digits=32)),
                ('realized_pnl', models.DecimalField(decimal_places=12, default=0, max_digits=32)),
                ('commission', models.DecimalField(decimal_places=12, default=0, max_digits=32)),
                ('commission_asset', models.CharField(blank=True, max_length=16)),
                ('executed_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='exchanges.exchangeaccount')),
            ],
            options={
                'ordering': ('-executed_at',),
                'indexes': [models.Index(fields=['account', '-executed_at'], name='trade_account_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'market', 'symbol', 'trade_id'), name='unique_binance_trade')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('total_value_usdt', models.DecimalField(decimal_places=12, max_digits=32)),
                ('spot_value_usdt', models.DecimalField(decimal_places=12, default=0, max_digits=32)),
                ('futures_value_usdt', models.DecimalField(decimal_places=12, default=0, max_digits=32)),
                ('source', models.CharField(choices=[('LIVE', 'Live Binance account'), ('ESTIMATED', 'Estimated from account income')], default='LIVE', max_length=16)),
                ('captured_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to='exchanges.exchangeaccount')),
            ],
            options={
                'ordering': ('snapshot_date',),
                'constraints': [models.UniqueConstraint(fields=('account', 'snapshot_date'), name='unique_daily_portfolio_snapshot')],
            },
        ),
    ]
