# Generated by Django 6.0.6 on 2026-08-03 13:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def copy_existing_binance_trades(apps, schema_editor):
    BinanceTrade = apps.get_model("exchanges", "BinanceTrade")
    TradeLog = apps.get_model("exchanges", "TradeLog")
    batch = []
    for trade in BinanceTrade.objects.select_related("account").iterator(chunk_size=500):
        batch.append(TradeLog(
            user_id=trade.account.user_id,
            account_id=trade.account_id,
            source="BINANCE",
            status="FILLED",
            market=trade.market,
            symbol=trade.symbol,
            trade_id=trade.trade_id,
            order_id=trade.order_id,
            side=trade.side,
            price=trade.price,
            quantity=trade.quantity,
            quote_quantity=trade.quote_quantity,
            realized_pnl=trade.realized_pnl,
            commission=trade.commission,
            commission_asset=trade.commission_asset,
            executed_at=trade.executed_at,
        ))
        if len(batch) == 500:
            TradeLog.objects.bulk_create(batch, batch_size=500)
            batch = []
    if batch:
        TradeLog.objects.bulk_create(batch, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0003_binancetrade_portfoliosnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(choices=[('BINANCE', 'Binance'), ('DRAFT', 'Draft / paper trade')], max_length=16)),
                ('status', models.CharField(choices=[('FILLED', 'Filled'), ('DRAFT', 'Draft'), ('CANCELLED', 'Cancelled')], max_length=16)),
                ('market', models.CharField(choices=[('FUTURES', 'USD-M Futures'), ('SPOT', 'Spot')], max_length=16)),
                ('symbol', models.CharField(max_length=32)),
                ('trade_id', models.BigIntegerField(blank=True, null=True)),
                ('order_id', models.BigIntegerField(blank=True, null=True)),
                ('side', models.CharField(max_length=8)),
                ('price', models.DecimalField(decimal_places=12, max_digits=32)),
                ('quantity', models.DecimalField(decimal_places=12, max_digits=32)),
                ('quote_quantity', models.DecimalField(decimal_places=12, default=0, max_digits=32)),
                ('realized_pnl', models.DecimalField(decimal_places=12, default=0, max_digits=32)),
                ('commission', models.DecimalField(decimal_places=12, default=0, max_digits=32)),
                ('commission_asset', models.CharField(blank=True, max_length=16)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=12, max_digits=32, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=12, max_digits=32, null=True)),
                ('leverage', models.PositiveSmallIntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-executed_at',),
            },
        ),
        migrations.CreateModel(
            name='TradeSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('FUTURES', 'USD-M Futures'), ('SPOT', 'Spot')], max_length=16)),
                ('symbol', models.CharField(max_length=32)),
                ('last_trade_id', models.BigIntegerField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='binancetrade',
            name='trade_account_time_idx',
        ),
        migrations.RemoveConstraint(
            model_name='binancetrade',
            name='unique_binance_trade',
        ),
        migrations.AddField(
            model_name='tradelog',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_logs', to='exchanges.exchangeaccount'),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tradesyncstate',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_sync_states', to='exchanges.exchangeaccount'),
        ),
        migrations.RunPython(copy_existing_binance_trades, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='binancetrade',
            name='account',
        ),
        migrations.AddIndex(
            model_name='tradelog',
            index=models.Index(fields=['user', '-executed_at'], name='tradelog_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='tradelog',
            index=models.Index(fields=['user', 'source', '-executed_at'], name='tradelog_user_src_time_idx'),
        ),
        migrations.AddIndex(
            model_name='tradelog',
            index=models.Index(fields=['user', 'market', 'side', '-executed_at'], name='tradelog_user_filter_idx'),
        ),
        migrations.AddConstraint(
            model_name='tradelog',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'BINANCE')), fields=('account', 'market', 'symbol', 'trade_id'), name='unique_real_binance_trade'),
        ),
        migrations.AddConstraint(
            model_name='tradesyncstate',
            constraint=models.UniqueConstraint(fields=('account', 'market', 'symbol'), name='unique_trade_sync_cursor'),
        ),
        migrations.DeleteModel(
            name='BinanceTrade',
        ),
    ]
