# Generated by Django 6.0.6 on 2026-08-10 02:51

import django.core.validators
import django.db.models.deletion
import exchanges.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveBigIntegerField()),
                ('api_hash', exchanges.fields.EncryptedTextField()),
                ('session', exchanges.fields.EncryptedTextField(blank=True, default='')),
                ('phone', exchanges.fields.EncryptedTextField(blank=True, default='')),
                ('phone_hint', models.CharField(blank=True, max_length=32)),
                ('phone_code_hash', exchanges.fields.EncryptedTextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Waiting for verification'), ('CONNECTED', 'Connected'), ('ERROR', 'Error'), ('DISABLED', 'Disabled')], default='PENDING', max_length=16)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('challenge_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CopyStrategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField()),
                ('chat_title', models.CharField(max_length=255)),
                ('chat_username', models.CharField(blank=True, max_length=255)),
                ('mode', models.CharField(choices=[('PAPER', 'Paper trading'), ('LIVE', 'Live Binance Futures')], default='PAPER', max_length=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Listening'), ('PAUSED', 'Paused'), ('ERROR', 'Error')], default='ACTIVE', max_length=12)),
                ('allocation_usdt', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_leverage', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(125)])),
                ('max_daily_loss_usdt', models.DecimalField(decimal_places=8, default=50, max_digits=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('allowed_symbols', models.JSONField(blank=True, default=list)),
                ('last_message_id', models.BigIntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_strategies', to=settings.AUTH_USER_MODEL)),
                ('telegram_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='copytrading.telegramconnection')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_message_id', models.BigIntegerField()),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField()),
                ('parse_status', models.CharField(choices=[('SIGNAL', 'Trading signal'), ('IGNORED', 'Ignored'), ('INVALID', 'Invalid signal')], default='IGNORED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='copytrading.copystrategy')),
            ],
            options={
                'ordering': ('-sent_at',),
            },
        ),
        migrations.CreateModel(
            name='TradeSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=8)),
                ('entry_low', models.DecimalField(decimal_places=12, max_digits=32)),
                ('entry_high', models.DecimalField(decimal_places=12, max_digits=32)),
                ('stop_loss', models.DecimalField(decimal_places=12, max_digits=32)),
                ('take_profits', models.JSONField(default=list)),
                ('requested_leverage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parser_version', models.CharField(default='chn-v1', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal', to='copytrading.telegrammessage')),
            ],
        ),
        migrations.CreateModel(
            name='CopyExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PAPER_FILLED', 'Paper filled'), ('SUBMITTED', 'Submitted'), ('PROTECTED', 'TP/SL protected'), ('SKIPPED', 'Skipped by risk checks'), ('FAILED', 'Failed')], max_length=16)),
                ('symbol', models.CharField(max_length=32)),
                ('direction', models.CharField(max_length=8)),
                ('entry_price', models.DecimalField(decimal_places=12, max_digits=32)),
                ('quantity', models.DecimalField(decimal_places=12, default=0, max_digits=32)),
                ('leverage', models.PositiveSmallIntegerField(default=1)),
                ('margin_usdt', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('stop_loss', models.DecimalField(decimal_places=12, max_digits=32)),
                ('take_profit', models.DecimalField(decimal_places=12, max_digits=32)),
                ('entry_order_id', models.CharField(blank=True, max_length=64)),
                ('stop_order_id', models.CharField(blank=True, max_length=64)),
                ('take_profit_order_id', models.CharField(blank=True, max_length=64)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='copytrading.copystrategy')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='copytrading.tradesignal')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='copystrategy',
            index=models.Index(fields=['status', 'updated_at'], name='copy_strategy_worker_idx'),
        ),
        migrations.AddConstraint(
            model_name='copystrategy',
            constraint=models.UniqueConstraint(fields=('user', 'chat_id'), name='unique_user_copy_chat'),
        ),
        migrations.AddIndex(
            model_name='telegrammessage',
            index=models.Index(fields=['strategy', '-sent_at'], name='telegram_strategy_time_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammessage',
            index=models.Index(fields=['strategy', 'parse_status', '-sent_at'], name='telegram_parse_idx'),
        ),
        migrations.AddConstraint(
            model_name='telegrammessage',
            constraint=models.UniqueConstraint(fields=('strategy', 'telegram_message_id'), name='unique_telegram_message'),
        ),
        migrations.AddIndex(
            model_name='copyexecution',
            index=models.Index(fields=['strategy', '-created_at'], name='copy_execution_time_idx'),
        ),
        migrations.AddIndex(
            model_name='copyexecution',
            index=models.Index(fields=['strategy', 'status', '-created_at'], name='copy_execution_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='copyexecution',
            constraint=models.UniqueConstraint(fields=('strategy', 'signal'), name='unique_copy_execution'),
        ),
    ]
