# Generated by Django 6.0.6 on 2026-08-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='media_file',
            field=models.FileField(blank=True, upload_to='copy_trading_media/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='media_mime_type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='media_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='media_type',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
