# Generated by Django 6.0.6 on 2026-08-10 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0002_telegrammessage_media_file_and_more'),
        ('exchanges', '0004_tradelog_tradesyncstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyexecution',
            name='close_reason',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='copyexecution',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='copyexecution',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='copyexecution',
            name='position_status',
            field=models.CharField(choices=[('NONE', 'No position'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], default='NONE', max_length=8),
        ),
        migrations.AddField(
            model_name='copyexecution',
            name='realized_pnl',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name='copyexecution',
            name='trade_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copy_execution', to='exchanges.tradelog'),
        ),
        migrations.AddIndex(
            model_name='copyexecution',
            index=models.Index(fields=['strategy', 'position_status', '-created_at'], name='copy_position_status_idx'),
        ),
    ]
