# Generated by Django 6.0.6 on 2026-08-10 08:56

from django.db import migrations, models


def preserve_existing_manual_caps(apps, schema_editor):
    CopyStrategy = apps.get_model('copytrading', 'CopyStrategy')
    CopyStrategy.objects.update(use_binance_max_leverage=False)


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0003_copyexecution_close_reason_copyexecution_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copystrategy',
            name='use_binance_max_leverage',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(preserve_existing_manual_caps, migrations.RunPython.noop),
    ]
