# Generated by Django 6.0.6 on 2026-08-23 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0006_copystrategy_entry_tolerance_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyexecution',
            name='entry_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='copyexecution',
            name='entry_order_type',
            field=models.CharField(default='MARKET', max_length=8),
        ),
        migrations.AddField(
            model_name='copyexecution',
            name='limit_price',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='copystrategy',
            name='entry_order_type',
            field=models.CharField(choices=[('MARKET', 'Market entry'), ('LIMIT', 'Limit entry')], default='MARKET', max_length=8),
        ),
        migrations.AddField(
            model_name='copystrategy',
            name='limit_expiry_minutes',
            field=models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='copyexecution',
            name='position_status',
            field=models.CharField(choices=[('NONE', 'No position'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('PENDING', 'Pending entry')], default='NONE', max_length=8),
        ),
        migrations.AlterField(
            model_name='copyexecution',
            name='status',
            field=models.CharField(choices=[('PAPER_FILLED', 'Paper filled'), ('SUBMITTED', 'Submitted'), ('PROTECTED', 'TP/SL protected'), ('SKIPPED', 'Skipped by risk checks'), ('FAILED', 'Failed'), ('PENDING_ENTRY', 'Waiting for limit entry'), ('CANCELLED', 'Entry cancelled')], max_length=16),
        ),
    ]
