# Generated by Django 6.0.6 on 2026-08-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0007_copyexecution_entry_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copystrategy',
            name='entry_order_type',
            field=models.CharField(choices=[('MARKET', 'Market entry'), ('LIMIT', 'Limit entry'), ('SMART', 'Market with limit fallback')], default='SMART', max_length=8),
        ),
    ]
