# Generated by Django 6.0.6 on 2026-08-23 13:36

import django.core.validators
import django.db.models.deletion
import exchanges.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0008_alter_copystrategy_entry_order_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='copystrategy',
            name='ai_detection_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AISignalAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('OPENAI', 'OpenAI')], default='OPENAI', max_length=16)),
                ('api_key', exchanges.fields.EncryptedTextField()),
                ('api_key_hint', models.CharField(blank=True, max_length=16)),
                ('model', models.CharField(default='gpt-5-nano', max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('min_confidence', models.DecimalField(decimal_places=3, default=Decimal('0.900'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.500')), django.core.validators.MaxValueValidator(Decimal('1.000'))])),
                ('daily_call_limit', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('ERROR', 'Error'), ('DISABLED', 'Disabled')], default='CONNECTED', max_length=16)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_signal_agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AISignalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('SIGNAL', 'Signal'), ('NOT_SIGNAL', 'Not a signal'), ('LOW_CONFIDENCE', 'Low confidence'), ('ERROR', 'Error')], max_length=16)),
                ('confidence', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('result', models.JSONField(default=dict)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_signal_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_signal_user_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_hash', 'provider', 'model', 'prompt_version'), name='unique_ai_signal_analysis')],
            },
        ),
    ]
