# Generated by Django 6.0.6 on 2026-08-23 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0009_copystrategy_ai_detection_enabled_aisignalagent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='parse_status',
            field=models.CharField(choices=[('SIGNAL', 'Trading signal'), ('REVIEW', 'Needs user review'), ('IGNORED', 'Ignored'), ('INVALID', 'Invalid signal')], default='IGNORED', max_length=12),
        ),
        migrations.CreateModel(
            name='SignalCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=8)),
                ('target_hint', models.CharField(blank=True, max_length=64)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Waiting for review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal_candidate', to='copytrading.telegrammessage')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-created_at'], name='signal_candidate_status_idx')],
            },
        ),
    ]
