# Generated by Django 6.0.6 on 2026-08-27 16:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0011_copyexecution_binance_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='copystrategy',
            name='minimum_risk_reward',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('20.00'))]),
        ),
        migrations.AddField(
            model_name='copystrategy',
            name='risk_percent_per_order',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
