# Generated by Django 6.0.6 on 2026-08-27 16:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def backfill_execution_quantities(apps, schema_editor):
    CopyExecution = apps.get_model("copytrading", "CopyExecution")
    CopyExecution.objects.update(
        remaining_quantity=models.F("quantity"),
        take_profit_quantity=models.F("quantity"),
        tp1_close_percent=Decimal("100.00"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0012_copystrategy_minimum_risk_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyexecution',
            name='break_even_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='copyexecution',
            name='break_even_stop_order_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='copyexecution',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name='copyexecution',
            name='take_profit_quantity',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name='copyexecution',
            name='tp1_close_percent',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='copystrategy',
            name='tp1_close_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.RunPython(backfill_execution_quantities, migrations.RunPython.noop),
    ]
