# Generated by Django 6.0.6 on 2026-08-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0013_copyexecution_break_even_activated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyexecution',
            name='runner_take_profit',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='copyexecution',
            name='runner_take_profit_order_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
