# Generated by Django 6.0.6 on 2026-08-27 17:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def upgrade_previous_defaults(apps, schema_editor):
    CopyStrategy = apps.get_model('copytrading', 'CopyStrategy')
    CopyStrategy.objects.filter(risk_percent_per_order=Decimal('20.00')).update(
        risk_percent_per_order=Decimal('30.00')
    )
    CopyStrategy.objects.filter(minimum_risk_reward=Decimal('1.00')).update(
        minimum_risk_reward=Decimal('1.50')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0014_copyexecution_runner_take_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copystrategy',
            name='minimum_risk_reward',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('20.00'))]),
        ),
        migrations.AlterField(
            model_name='copystrategy',
            name='risk_percent_per_order',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.RunPython(upgrade_previous_defaults, migrations.RunPython.noop),
    ]
