# Generated by Django 6.0.6 on 2026-08-23 15:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('indicator_code', models.TextField(max_length=20000)),
                ('long_condition', models.CharField(max_length=1000)),
                ('short_condition', models.CharField(blank=True, max_length=1000)),
                ('parsed_spec', models.JSONField(blank=True, default=dict)),
                ('risk_reward_ratio', models.DecimalField(decimal_places=2, default=Decimal('2'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('stop_loss_percent', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('20'))])),
                ('symbols', models.JSONField(default=list)),
                ('timeframes', models.JSONField(default=list)),
                ('history_days', models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(365)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('TRAINING', 'Training'), ('TRAINED', 'Trained'), ('FAILED', 'Failed')], default='DRAFT', max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='StrategyRuntime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('PAPER', 'Paper'), ('LIVE', 'Live Binance Futures')], default='PAPER', max_length=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ERROR', 'Error')], default='ACTIVE', max_length=12)),
                ('symbols', models.JSONField(default=list)),
                ('timeframes', models.JSONField(default=list)),
                ('allocation_per_order', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('total_budget', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('max_daily_loss', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('leverage', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(125)])),
                ('max_open_positions', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('last_candles', models.JSONField(blank=True, default=dict)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtimes', to='strategy_lab.strategydefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_runtimes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StrategyPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=32)),
                ('timeframe', models.CharField(max_length=8)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=8)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('FAILED', 'Failed')], default='OPEN', max_length=8)),
                ('entry_price', models.DecimalField(decimal_places=12, max_digits=32)),
                ('current_price', models.DecimalField(decimal_places=12, max_digits=32)),
                ('quantity', models.DecimalField(decimal_places=12, max_digits=32)),
                ('leverage', models.PositiveSmallIntegerField(default=1)),
                ('margin_usdt', models.DecimalField(decimal_places=8, max_digits=20)),
                ('stop_loss', models.DecimalField(decimal_places=12, max_digits=32)),
                ('take_profit', models.DecimalField(decimal_places=12, max_digits=32)),
                ('unrealized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('entry_order_id', models.CharField(blank=True, max_length=64)),
                ('stop_order_id', models.CharField(blank=True, max_length=64)),
                ('take_profit_order_id', models.CharField(blank=True, max_length=64)),
                ('signal_candle_time', models.BigIntegerField()),
                ('close_reason', models.CharField(blank=True, max_length=32)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('runtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='strategy_lab.strategyruntime')),
            ],
            options={
                'ordering': ('-opened_at',),
            },
        ),
        migrations.CreateModel(
            name='StrategyTrainingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=12)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('config_snapshot', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_runs', to='strategy_lab.strategydefinition')),
            ],
            options={
                'ordering': ('-queued_at',),
            },
        ),
        migrations.AddField(
            model_name='strategyruntime',
            name='training_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runtimes', to='strategy_lab.strategytrainingrun'),
        ),
        migrations.CreateModel(
            name='StrategyBacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('timeframe', models.CharField(max_length=8)),
                ('bars_tested', models.PositiveIntegerField(default=0)),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('winning_trades', models.PositiveIntegerField(default=0)),
                ('losing_trades', models.PositiveIntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('net_return_percent', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('profit_factor', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('max_drawdown_percent', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('trades', models.JSONField(default=list)),
                ('equity_curve', models.JSONField(default=list)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('training_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='strategy_lab.strategytrainingrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='strategydefinition',
            index=models.Index(fields=['user', '-updated_at'], name='strategy_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='strategydefinition',
            index=models.Index(fields=['status', 'updated_at'], name='strategy_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyposition',
            index=models.Index(fields=['runtime', 'status', '-opened_at'], name='position_runtime_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyposition',
            index=models.Index(fields=['runtime', '-opened_at'], name='position_history_idx'),
        ),
        migrations.AddConstraint(
            model_name='strategyposition',
            constraint=models.UniqueConstraint(fields=('runtime', 'symbol', 'timeframe', 'signal_candle_time'), name='unique_runtime_signal_candle'),
        ),
        migrations.AddIndex(
            model_name='strategytrainingrun',
            index=models.Index(fields=['status', 'queued_at'], name='training_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='strategytrainingrun',
            index=models.Index(fields=['strategy', '-queued_at'], name='training_strategy_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyruntime',
            index=models.Index(fields=['status', 'updated_at'], name='runtime_worker_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyruntime',
            index=models.Index(fields=['user', '-created_at'], name='runtime_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='strategybacktestresult',
            index=models.Index(fields=['training_run', '-win_rate'], name='backtest_run_win_idx'),
        ),
        migrations.AddConstraint(
            model_name='strategybacktestresult',
            constraint=models.UniqueConstraint(fields=('training_run', 'symbol', 'timeframe'), name='unique_training_market'),
        ),
    ]
