# Generated by Django 6.0.6 on 2026-08-28 08:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyruntime',
            name='minimum_risk_reward',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('20.00'))]),
        ),
        migrations.AddField(
            model_name='strategyruntime',
            name='risk_percent_per_order',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='strategyruntime',
            name='use_binance_max_leverage',
            field=models.BooleanField(default=True),
        ),
    ]
