# Generated by Django 6.0.6 on 2026-08-23 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnl_alerts', models.BooleanField(default=True)),
                ('trade_execution_alerts', models.BooleanField(default=True)),
                ('copy_message_notifications', models.BooleanField(default=True)),
                ('copy_signal_notifications', models.BooleanField(default=True)),
                ('system_alerts', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
